#!/usr/bin/env python3
"""
Question Generator - Create learning items for knowledge components

This script generates multiple-choice questions and maps them to knowledge components.
In production, you could integrate with OpenAI/Claude to generate questions automatically.

Usage:
    python -m scripts.generate_questions
    # or
    python scripts/generate_questions.py
"""

from database import Database
from pymongo.errors import DuplicateKeyError

# Sample questions for each skill
# In production, these could be generated by an LLM
SAMPLE_QUESTIONS = {
    "checking-accounts": [
        {
            "stem": "What is the main purpose of a checking account?",
            "choices": [
                "To earn high interest on savings",
                "To handle everyday transactions like paying bills",
                "To invest in stocks",
                "To get a loan from the bank"
            ],
            "correct_answer": 1,  # Index of correct choice (0-based)
            "explanation": "Checking accounts are designed for frequent transactions - depositing paychecks, paying bills, and daily purchases. Unlike savings accounts, they typically don't earn much interest.",
            "difficulty": 0.3,
            "discrimination": 1.0,
            "visa_variants": {}
        },
        {
            "stem": "What is a common fee that banks charge on checking accounts?",
            "choices": [
                "Monthly maintenance fee",
                "Breathing fee",
                "Deposit fee",
                "Paper fee"
            ],
            "correct_answer": 0,
            "explanation": "Many banks charge a monthly maintenance fee, though this can often be waived by maintaining a minimum balance or setting up direct deposit.",
            "difficulty": 0.4,
            "discrimination": 1.1,
            "visa_variants": {
                "F1": {
                    "additional_context": "As a student, look for student checking accounts that waive monthly fees."
                }
            }
        },
        {
            "stem": "What happens if you write a check for more money than you have in your account?",
            "choices": [
                "The bank automatically deposits money to cover it",
                "Your account may be charged an overdraft fee",
                "Nothing happens",
                "The check automatically cancels"
            ],
            "correct_answer": 1,
            "explanation": "This is called an overdraft. Banks may charge $30-$35 per overdraft, and the check may bounce. Some banks offer overdraft protection to avoid this.",
            "difficulty": 0.5,
            "discrimination": 1.2
        }
    ],

    "credit-score-factors": [
        {
            "stem": "Which factor has the BIGGEST impact on your credit score?",
            "choices": [
                "Credit mix (types of credit)",
                "Payment history",
                "Length of credit history",
                "New credit inquiries"
            ],
            "correct_answer": 1,
            "explanation": "Payment history makes up about 35% of your FICO score - the largest single factor. Paying on time every time is the most important thing you can do for your credit.",
            "difficulty": 0.5,
            "discrimination": 1.3,
            "visa_variants": {
                "H1B": {
                    "additional_context": "Building strong payment history is crucial as you start your credit journey in the US."
                }
            }
        },
        {
            "stem": "What percentage of your credit limit should you ideally use to maintain a good credit score?",
            "choices": [
                "100% - max it out",
                "Under 30%",
                "Exactly 50%",
                "It doesn't matter"
            ],
            "correct_answer": 1,
            "explanation": "Credit utilization (how much you use vs. your limit) should stay under 30%, ideally under 10%. This shows you're not relying too heavily on credit.",
            "difficulty": 0.6,
            "discrimination": 1.2
        },
        {
            "stem": "How long do negative marks (like late payments) typically stay on your credit report?",
            "choices": [
                "1 year",
                "3 years",
                "7 years",
                "Forever"
            ],
            "correct_answer": 2,
            "explanation": "Most negative information stays on your credit report for 7 years, though bankruptcies can stay for 10 years. The impact lessens over time.",
            "difficulty": 0.7,
            "discrimination": 1.0
        }
    ],

    "building-credit": [
        {
            "stem": "What is a good first step to start building credit in the US if you have no credit history?",
            "choices": [
                "Apply for multiple credit cards at once",
                "Get a secured credit card",
                "Take out a large loan",
                "Wait until you have more money"
            ],
            "correct_answer": 1,
            "explanation": "A secured credit card requires a deposit (usually $200-$500) that becomes your credit limit. It's designed for people building credit and reports to credit bureaus.",
            "difficulty": 0.4,
            "discrimination": 1.4,
            "visa_variants": {
                "H1B": {
                    "additional_context": "Many H1B holders start with secured cards since they have no US credit history."
                },
                "F1": {
                    "additional_context": "Student credit cards are another option if you're on an F1 visa."
                }
            }
        },
        {
            "stem": "How long does it typically take to build a good credit score from scratch?",
            "choices": [
                "1-2 months",
                "6-12 months",
                "2-3 years",
                "5+ years"
            ],
            "correct_answer": 1,
            "explanation": "With responsible use (paying on time, low utilization), you can build a good credit score (700+) in 6-12 months. It takes consistency and patience.",
            "difficulty": 0.5,
            "discrimination": 1.0
        }
    ],

    "50-30-20-rule": [
        {
            "stem": "In the 50/30/20 budget rule, what does the 50% represent?",
            "choices": [
                "Wants and entertainment",
                "Savings and debt repayment",
                "Needs (rent, food, utilities)",
                "Investments"
            ],
            "correct_answer": 2,
            "explanation": "50% goes to needs (housing, food, transportation, utilities), 30% to wants (entertainment, dining out), and 20% to savings and debt repayment.",
            "difficulty": 0.4,
            "discrimination": 1.1
        },
        {
            "stem": "According to the 50/30/20 rule, if you earn $3,000/month after taxes, how much should go to savings?",
            "choices": [
                "$300",
                "$600",
                "$900",
                "$1,500"
            ],
            "correct_answer": 1,
            "explanation": "20% of $3,000 = $600 should go to savings and debt repayment each month. This builds your financial safety net.",
            "difficulty": 0.6,
            "discrimination": 1.3
        }
    ],

    "401k-basics": [
        {
            "stem": "What is the main advantage of contributing to a traditional 401(k)?",
            "choices": [
                "You can withdraw money anytime without penalty",
                "Contributions reduce your taxable income now",
                "The money is never taxed",
                "Your employer always matches 100%"
            ],
            "correct_answer": 1,
            "explanation": "Traditional 401(k) contributions are pre-tax, meaning they reduce your taxable income for the current year. You pay taxes when you withdraw in retirement.",
            "difficulty": 0.5,
            "discrimination": 1.2
        },
        {
            "stem": "At what age can you typically withdraw from a 401(k) without penalty?",
            "choices": [
                "55",
                "59½",
                "62",
                "65"
            ],
            "correct_answer": 1,
            "explanation": "The IRS penalty-free withdrawal age is 59½. Withdrawing before that typically incurs a 10% penalty plus income taxes.",
            "difficulty": 0.7,
            "discrimination": 1.0
        }
    ],

    "itin-vs-ssn": [
        {
            "stem": "What is the main difference between an ITIN and an SSN?",
            "choices": [
                "ITIN is for taxes only, SSN allows work authorization",
                "They are the same thing",
                "ITIN is only for citizens",
                "SSN is only for taxes"
            ],
            "correct_answer": 0,
            "explanation": "ITIN (Individual Taxpayer Identification Number) is issued by the IRS for tax purposes only. SSN (Social Security Number) is issued by SSA and authorizes work.",
            "difficulty": 0.4,
            "discrimination": 1.5,
            "visa_variants": {
                "H1B": {
                    "additional_context": "H1B holders are eligible for SSN and should apply for it to file taxes and work legally."
                }
            }
        },
        {
            "stem": "Who should apply for an ITIN?",
            "choices": [
                "Anyone who needs a tax ID but isn't eligible for SSN",
                "Only US citizens",
                "Only undocumented immigrants",
                "People who want two tax IDs"
            ],
            "correct_answer": 0,
            "explanation": "ITIN is for anyone who has a tax filing requirement but doesn't have and isn't eligible for an SSN - this includes dependents, spouses of visa holders, and certain non-residents.",
            "difficulty": 0.5,
            "discrimination": 1.2
        }
    ],

    "understanding-paystubs": [
        {
            "stem": "What does 'gross pay' on your paystub mean?",
            "choices": [
                "The amount after all deductions",
                "Your total earnings before any deductions",
                "Only your overtime pay",
                "Your bonus amount"
            ],
            "correct_answer": 1,
            "explanation": "Gross pay is your total earnings before taxes and other deductions. Your 'net pay' (take-home) is what remains after deductions.",
            "difficulty": 0.3,
            "discrimination": 1.2
        },
        {
            "stem": "What does 'FICA' on your paystub stand for?",
            "choices": [
                "Federal Income Credit Assessment",
                "Federal Insurance Contributions Act",
                "Foreign Income Collection Agency",
                "Financial Institution Compliance Act"
            ],
            "correct_answer": 1,
            "explanation": "FICA is Social Security and Medicare taxes - 7.65% of your gross pay (6.2% Social Security + 1.45% Medicare). Your employer matches this amount.",
            "difficulty": 0.6,
            "discrimination": 1.0
        }
    ],

    "what-is-investing": [
        {
            "stem": "What is the main difference between saving and investing?",
            "choices": [
                "There is no difference",
                "Saving is for short-term goals, investing is for long-term growth",
                "Saving earns more money than investing",
                "You can only invest if you're rich"
            ],
            "correct_answer": 1,
            "explanation": "Saving is typically for short-term needs and keeps money safe (in savings accounts). Investing is for long-term goals and involves risk for potentially higher returns.",
            "difficulty": 0.3,
            "discrimination": 1.1
        },
        {
            "stem": "Why is starting to invest early important?",
            "choices": [
                "You'll get better interest rates when you're young",
                "Compound interest has more time to grow your money",
                "Stocks are cheaper for young people",
                "It's not important when you start"
            ],
            "correct_answer": 1,
            "explanation": "Compound interest means your money earns returns, and those returns earn returns. Starting early gives compound interest decades to work magic - even small amounts can grow significantly.",
            "difficulty": 0.4,
            "discrimination": 1.3
        }
    ]
}


def insert_questions():
    """Insert all sample questions into the database"""
    print("="*80)
    print("GENERATING LEARNING ITEMS (QUESTIONS)")
    print("="*80)

    # Initialize database
    db = Database()

    if not db.is_connected:
        print("\n❌ Cannot connect to database. Check your MONGO_URI in .env")
        return False

    print(f"\n📝 Processing {len(SAMPLE_QUESTIONS)} skill categories...")

    total_created = 0
    total_skipped = 0
    total_errors = 0
    total_mappings = 0

    for skill_slug, questions in SAMPLE_QUESTIONS.items():
        print(f"\n  Processing '{skill_slug}'...")

        # Find the knowledge component
        skill = db.collections.knowledge_components.find_one({"slug": skill_slug})

        if not skill:
            print(f"    ❌ Knowledge component not found: {skill_slug}")
            print(f"       Run: python -m scripts.seed_skills")
            total_errors += len(questions)
            continue

        skill_id = str(skill['_id'])
        created_for_skill = 0

        for q in questions:
            try:
                # Create the learning item
                item_id = db.collections.create_learning_item(
                    item_type='multiple_choice',
                    content={
                        'stem': q['stem'],
                        'choices': q['choices'],
                        'correct_answer': q['correct_answer'],
                        'explanation': q['explanation'],
                        'visa_variants': q.get('visa_variants', {})
                    },
                    difficulty=q.get('difficulty', 0.5),
                    discrimination=q.get('discrimination', 1.0),
                    allows_llm_personalization=True
                )

                # Create item-KC mapping
                try:
                    db.collections.create_item_kc_mapping(
                        item_id=item_id,
                        kc_id=skill_id,
                        weight=1.0
                    )
                    total_mappings += 1
                except DuplicateKeyError:
                    pass  # Mapping already exists

                created_for_skill += 1
                total_created += 1

            except Exception as e:
                print(f"    ❌ Error creating question: {e}")
                total_errors += 1

        print(f"    ✓ Created {created_for_skill} questions for '{skill_slug}'")

    # Summary
    print("\n" + "="*80)
    print("QUESTION GENERATION COMPLETE")
    print("="*80)
    print(f"\n📊 Summary:")
    print(f"  • Questions Created: {total_created}")
    print(f"  • Skipped: {total_skipped}")
    print(f"  • Errors: {total_errors}")
    print(f"  • Item-KC Mappings: {total_mappings}")

    print(f"\n📚 Questions by Skill:")
    for skill_slug, questions in SAMPLE_QUESTIONS.items():
        print(f"  • {skill_slug}: {len(questions)} questions")

    print("\n💡 Next Steps:")
    print("  • Generate more questions for other skills")
    print("  • Use LLM integration to auto-generate questions")
    print("  • Add different question types (fill-in-blank, scenario, etc.)")
    print("\n✅ Learning items seeded successfully!\n")

    return True


if __name__ == "__main__":
    insert_questions()
